# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 00:12
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0002_remove_location_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='40.77, 73.98', max_length=100),
        ),
    ]
