# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 00:22
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0003_auto_20170602_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
