# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0004_auto_20170602_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='url',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Geo Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endDateTime',
            field=models.DateTimeField(verbose_name='End Date/Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='foodtruck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTrucker.FoodTruck', verbose_name='Food Truck Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTrucker.Location', verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDateTime',
            field=models.DateTimeField(verbose_name='Start Date/Time'),
        ),
    ]
