# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0005_auto_20170602_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtruck',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['startDateTime']},
        ),
    ]
