# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0009_auto_20170604_1251'),
    ]

    operations = [
        migrations.RenameField('Schedule', 'location', 'venue')
    ]
