# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0010_auto_20170604_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTrucker.Venue', verbose_name='Venue Name'),
        ),
    ]
