# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0012_auto_20170604_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='venue',
            name='url',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
