# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0014_auto_20170604_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\d{3}\\-\\d{3}\\-\\d{4}$')], verbose_name='Phone Number'),
        ),
    ]
