# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0015_auto_20170604_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodTrucker.VenueType', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
