# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0018_auto_20170604_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='updateNotes',
            field=models.TextField(blank=True, verbose_name='Update Notes'),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='updateURL',
            field=models.URLField(blank=True, verbose_name='Update Website'),
        ),
    ]
