# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0019_auto_20170604_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruckType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Food Type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodTrucker.FoodTruckType', verbose_name='Type'),
            preserve_default=False,
        ),
    ]
