# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTrucker', '0020_auto_20170604_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtrucktype',
            options={'ordering': ['name'], 'verbose_name': 'Food Truck Type'},
        ),
    ]
